-- [IV] DDL, DCL, DML 
/* SQL
 - DCL 
    사용자 계정생성 CREATE USER, 권한부여 GRANT, 권한박탈 REVOKE, 사용자 계정삭제 DROP USER
    트랜젝션 명령어
 - DDL
    테이블 생성 CREATE TABLE , 테이블 삭제 DROP TABLE 
    테이블 구조변경 ALTER TABLE
 - DML
    데이터 삽입 INSERT, 조회 SELECT, 수정 UPDATE, 삭제 DELETE
*/
--------------------------
-------- ★ DDL ★ --------
--------------------------
-- 1. 테이블 생성(CREATE TABLE 테이블명) : 테이블 구조를 정의
CREATE TABLE BOOK(
    BOOKID NUMBER(4),  -- BOOKID 라는 필드에 숫자 4자리
    BOOKNAME VARCHAR2(20), -- BOOKNAME 필드의 타입은 문자 20BYTE
    PUBLISHER VARCHAR2(20),
    RDATE   DATE,           -- RDATE 필드의 타입은 DATE형
    PRICE    NUMBER(8,2),  -- PRICE 필드의 타입은 숫자 전체 자리 8자리 중 소숫점 2자리    
    PRIMARY KEY(BOOKID)  -- 프라이머리키 제약조건을 선언 (NOT NULL, UNIQUE)
    );
SELECT * FROM BOOK;
DESC BOOK;

DROP TABLE BOOK;  -- 2. 테이블 삭제

CREATE TABLE BOOK(   
    BID NUMBER(4) PRIMARY KEY,
    BNAME VARCHAR2(20),
    PUBLISHER VARCHAR2(20),
    RDATE DATE,
    PRICE NUMBER(8)
);

-- EX. DEPT01 테이블 만들기
CREATE TABLE DEPT01(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
    );
    
SELECT * FROM DEPT01;

SELECT * FROM DEPT;  -- 10, 20, 30, 40

SELECT DISTINCT DEPTNO FROM EMP; -- 10, 20, 30
DESC EMP;

INSERT INTO EMP (EMPNO, ENAME, DEPTNO) VALUES (9999, 'JINS', 40);
INSERT INTO EMP (EMPNO, ENAME, DEPTNO) VALUES (8888, 'HONG', 50);
SELECT * FROM EMP;
ROLLBACK; -- DML 취소 트랜젝션 명령어
SELECT * FROM EMP;
SELECT * FROM DEPT01;
CREATE TABLE EMP01(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    SAL NUMBER(7,2),
    DEPTNO NUMBER(2) REFERENCES DEPT01(DEPTNO)  -- FK 제약조건
);

DESC EMP01;
DROP TABLE EMP01;
DROP TABLE DEPT01;

CREATE TABLE EMP01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    SAL NUMBER(7,2),
    DEPTNO NUMBER(2), 
    PRIMARY KEY (EMPNO),
    FOREIGN KEY (DEPTNO) REFERENCES DEPT01(DEPTNO)  -- FK 제약조건
);

--------------------------
-------- ★ DML ★ --------
--------------------------

-- 1. INSERT INTO 
    -- 1) INSERT INTO 테이블이름 (필드명1, 필드명2, 필드명3, ...) VALUES (값1, 값2, 값3, ...);  
       -- 필드를 정해서 집어넣는 방식, 앞의 필드명 수와 값 개수가 같아야함
    -- 2) INSERT INTO 테이블이름 VALUES (값1, 값2, 값3, ..., 값N);  
        -- 전체 필드에 값을 넣는 방식, 전체 필드 수 만큼 값 개수가 필요

SELECT * FROM DEPT01;
SELECT * FROM EMP01;
SELECT * FROM BOOK;

INSERT INTO DEPT01 (DEPTNO, DNAME, LOC) VALUES (15, '재무', 'SEOUL');
INSERT INTO DEPT01 VALUES (50, '설계', 'BUSAN');
INSERT INTO DEPT01 VALUES (60, '큐레이션', 'SILLIM');
INSERT INTO DEPT01 (DEPTNO, LOC, DNAME ) VALUES (45, 'INCHEON', '지원');
INSERT INTO DEPT01 (DEPTNO, DNAME  ) VALUES (55, '설계');    -- 묵시적으로 NULL 입력
INSERT INTO DEPT01 (DEPTNO, DNAME, LOC  ) VALUES (90, '고객센터', NULL); -- 명시적으로 NULL 입력
SELECT * FROM DEPT01;
COMMIT; -- 트랜젝션 영역에 쌓여있는 DML 명령어 수행
SELECT * FROM DEPT01;
-- 서브쿼리를 이용한 INSERT
    --EX. DEPT테이블에서 10~30 부서의 내용을 DEPT01 테이블에 INSERT
    INSERT INTO DEPT01 SELECT * FROM DEPT WHERE DEPTNO < 40;
    SELECT * FROM DEPT01;
    COMMIT;
    
-- 연습문제 1
DROP TABLE SAM01;
CREATE TABLE SAM01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    SAL NUMBER(7,2),
    PRIMARY KEY(EMPNO)
);
INSERT INTO SAM01 VALUES(1000, 'APPLE', 'POLICE', 10000);
INSERT INTO SAM01 VALUES(1010, 'BANAN', 'NURSE', 15000);
INSERT INTO SAM01 VALUES(1020, 'ORANGE', 'DOCTOR', 25000);
INSERT INTO SAM01(EMPNO, ENAME, SAL) VALUES(1030, 'VERY', 25000);
INSERT INTO SAM01 VALUES(1040, 'CAT', NULL, 2000);

INSERT INTO SAM01 
    SELECT EMPNO, ENAME, JOB, SAL 
        FROM EMP
        WHERE DEPTNO=10;

SELECT * FROM SAM01;

-- 2. UPDATE 테이블명 SET 필드명1=값1[, 필드명2=값2, ... , 필드명N=값N] [WHERE 조건]
SELECT * FROM EMP01;
DROP TABLE EMP01;
CREATE TABLE EMP01
    AS SELECT * FROM EMP; 
SELECT * FROM EMP01;
    -- 부서번호를 30으로 수정
    UPDATE EMP01 SET DEPTNO=30;
    SELECT * FROM EMP01;
    ROLLBACK;
    -- 부서번호가 10인 사람들을 30번으로
    UPDATE EMP01 SET DEPTNO=30 WHERE DEPTNO=10;
    -- SOCOTT 의 부서번호를 30번으로, JOB은 'MANAGER'로 SAL과 COMM은 500$인상, 입사일은 오늘로
    UPDATE EMP01 
        SET DEPTNO=30, 
            JOB='MANAGER', 
            SAL = SAL+500, 
            COMM = NVL(COMM,0) + 500,
            -- HIREDATE = TO_DATE('25/06/04', 'YY/MM/DD') 
            HIREDATE = SYSDATE,  -- 오늘을 의미 
            MGR = (SELECT EMPNO FROM EMP WHERE ENAME ='KING')
        WHERE ENAME='SCOTT';
        SELECT * FROM EMP01 WHERE ENAME IN ('SCOTT', 'KING');
    -- 모든 직원 급여를 10% 인상
    UPDATE EMP01 SET SAL=SAL*1.1;
    SELECT * FROM EMP01;
    ROLLBACK;
    -- 급여가 3000 이상인 사원만 급여를 10% 인상
    UPDATE EMP01 SET SAL=SAL*1.1 WHERE SAL>=3000;
    SELECT * FROM EMP01;
    -- ‘DALLAS’에서근무하는직원들의월급을100인상
     UPDATE EMP01 
        SET SAL=SAL+100, 
            COMM = NVL(COMM, 0) +100
        WHERE DEPTNO = (SELECT DEPTNO
                                    FROM DEPT
                                    WHERE LOC = 'DALLAS');
                                    
    ROLLBACK;
    SELECT * FROM EMP01;
    -- EMP01에서 모든 사원의 급여와 입사일을 'KING'의 급여와 입사일로 수정
    UPDATE EMP01
        SET SAL = (SELECT SAL FROM EMP01 WHERE ENAME='KING'),
            HIREDATE = (SELECT HIREDATE FROM EMP01 WHERE ENAME='KING');
    SELECT * FROM EMP01;
    ROLLBACK;
    
-- 3. DELETE FROM 테이블명 [WHERE 조건];
DELETE FROM EMP01;
SELECT * FROM EMP01;
ROLLBACK;  -- INSERT, UPDATE, DELETE 만 취소 가능
DELETE FROM DEPT; -- violated - child record found

-- ※ 외래키 제약 조건 삭제 하면 삭제 가능하다.
-- ALTER TABLE 테이블명 DROP CONSTRAINT 외래키_제약조건명;
-- ALTER TABLE EMP DROP CONSTRAINT 'SYS_C006999'

-- ※ 외래키 제약조건 이름 확인
SELECT constraint_name
    FROM user_constraints
    WHERE table_name = 'EMP'
        AND constraint_type = 'R';  -- 'R'은 외래키(참조) 'P'는 프라이머리키
    
-- EX. 부서명이 RESEARCH인 부서인 직원을 삭제
    DELETE FROM EMP01 WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME='RESEARCH');
    SELECT * FROM EMP01;
-- SAM01에서 JOB이 정해지지 않은 사원 삭제
    DELETE FROM SAM01 WHERE JOB IS NULL;
    SELECT * FROM SAM01;
-- SAM01에서 이름이 'ORANGE' 삭제
    DELETE FROM SAM01 WHERE ENAME='ORANGE';
    
-- 연습문제 2
--1) MY_DATA 테이블을생성하시오. 단 ID가PRIMARY KEY이다
DROP TABLE MY_DATA;
CREATE TABLE MY_DATA(
    ID NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(10),
    USERID VARCHAR2(30),
    SALARY NUMBER(10,2)
);
SELECT * FROM MY_DATA;
--2) 값을 입력하는 SQL문을 작성 
INSERT INTO MY_DATA VALUES(1, 'Scott', 'sscott', 10000.00); 
INSERT INTO MY_DATA VALUES(2, 'Ford', 'fford', 13000.00);
INSERT INTO MY_DATA VALUES(3, 'Patel', 'pptel', 33000.00);
INSERT INTO MY_DATA VALUES(4, 'Report', 'rreport', 23500.00);
INSERT INTO MY_DATA VALUES(5, 'Good', 'ggood', 44450.00);
SELECT * FROM MY_DATA;
--3) SALARY의 숫자 형식 지정
-- TO_CHAR(날짜형데이터, 'YY/MM/DD HH:MI:SS')
-- TO_CHAR(숫자형데이터, '99,999.9')
SELECT ID "ID - number(4)", NAME "ID - VARCHAR2(10)", USERID "ID - VARCHAR2(30)", TO_CHAR(SALARY, '999,999.00') "SALARY - number(10,2)"
    FROM MY_DATA;
--4) 자료를영구적으로데이터베이스에등록하는명령어
COMMIT;
--5) ID 3번인 사람의 급여를 65000.00 으로갱신하고 영구적으로 데이터베이스에 반영
UPDATE MY_DATA
    SET SALARY = 65000
    WHERE ID=3;
COMMIT;
--6) NAME이 Ford인 사람을 삭제
DELETE FROM MY_DATA
    WHERE NAME = 'Ford';
SELECT * FROM MY_DATA;
COMMIT;
-- 7) SALARY가 15,000.00 이하인 사람의 급여를 15,000.00으로 변경
UPDATE MY_DATA
    SET SALARY = 15000
    WHERE SALARY < 15000;
SELECT * FROM MY_DATA;
-- 8) 위에서 생성한 테이블을 삭제
DROP TABLE MY_DATA;

-- 연습문제 3
SELECT * FROM EMP01;
-- 1) EMP 테이블과 같은구조와 같은내용의 테이블EMP01을생성 (테이블이있을시 제거한 후)
    DROP TABLE EMP01;
    CREATE TABLE EMP01
        AS SELECT * FROM EMP;
-- 2) 모든 사원의 급여를 10% 인상
    UPDATE EMP01
        SET SAL = SAL*1.1;
-- 3) 급여가 3000이상인 사원만 급여를 10%인상
    UPDATE EMP01
        SET SAL = SAL*1.1
        WHERE SAL >=3000;
    ROLLBACK;
-- 4) EMP01 테이블에서 ‘DALLAS’에서 근무하는 직원들의 월급을 1000 인상
    UPDATE EMP01
        SET SAL = SAL+1000
        WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS');
-- 5) SCOTT 사원의 부서번호는 20번으로, 직급은 MANAGER로 한꺼번에수정, 상위자를 KING으로 변경
    UPDATE EMP01
        SET DEPTNO=20, JOB='MANAGER', MGR = (SELECT EMPNO FROM EMP01 WHERE ENAME='KING')
        WHERE ENAME='SCOTT';
SELECT * FROM EMP01;
-- 6) 부서명이 SALES인 사원을 모두 삭제
    DELETE FROM EMP01
        WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');
-- 7) 사원명이 ‘FORD’인 사원을 삭제
    DELETE FROM EMP01
        WHERE ENAME='FORD';
-- 8) SAM01 테이블에서 JOB이 NULL인 사원을 삭제
    DELETE FROM SAM01
        WHERE JOB IS NULL;
-- 9) SAM01 테이블에서 ENAME이 ORANGE인 사원을 삭제
    DELETE FROM SAM01
        WHERE ENAME = 'ORANGE';

-- 10) 급여가 1500이하인 사람의 급여를 1500으로 수정
    UPDATE SAM01
        SET SAL = 1500
        WHERE SAL < 1500;
SELECT * FROM SAM01;

-- 11) JOB이 ‘MANAGER’인 사원의 급여를 10% 인하
    UPDATE SAM01
        SET SAL = SAL*.9
        WHERE JOB = 'MANAGER';
    SELECT * FROM SAM01;

-- ★ 제약조건 : INSERT, UPDATE할 때, 제약조건에 맞는 데이터만 INSERT, UPDATE
-- (1) PRIMARY KEY : 테이블의 각 행을 유일한 값으로 식별하기 위한 필드
-- (2) FOREIGN KEY : 테이블의 열이 다른 테이블의 열을 참조
-- (3) NOT NULL : NULL을 포함하지 않는 필드
-- (4) UNIQUE : 모든 행의 값이 유일한 값, 단 NULL 허용(NULL값 여러개도 가능)
-- (5) CHECK(조건) : 해당 조건이 만족(NULL값 허용)
-- (*) DEFAULT 기본값 : 해당 열의 데이터를 입력하지 않으면 기본값으로 설정(원래는 NULL이 들어감)

-- DEPT1 & EMP1 (ERD 작성 -> DDL)
-- exERD를 이용 (https://www.exerd.com/down.do)
    
DROP TABLE DEPT1;
CREATE TABLE DEPT1(
    DEPTNO NUMBER(2) NOT NULL,
    DNAME VARCHAR2(14) NOT NULL ,
    LOC VARCHAR2(13) NOT NULL,
    PRIMARY KEY(DEPTNO),
    UNIQUE(DNAME)
);

DROP TABLE EMP1;
CREATE TABLE EMP1(
    EMPNO NUMBER(4) NOT NULL  PRIMARY KEY,
    ENAME VARCHAR2(10) NOT NULL ,
    JOB VARCHAR2(9) NOT NULL,
    MGR NUMBER(4),
    HIREDATE DATE DEFAULT SYSDATE,
    SAL NUMBER(7,2) NOT NULL CHECK(SAL>0),
    COMM NUMBER(7,2) CHECK(COMM>=0),
    DEPTNO NUMBER(2) REFERENCES DEPT1(DEPTNO)
);

DROP TABLE EMP1;
CREATE TABLE EMP1(
    EMPNO NUMBER(4) NOT NULL,
    ENAME VARCHAR2(10) NOT NULL ,
    JOB VARCHAR2(9) NOT NULL,
    MGR NUMBER(4),
    HIREDATE DATE DEFAULT SYSDATE,
    SAL NUMBER(7,2) NOT NULL,
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2),
    PRIMARY KEY (EMPNO),
    FOREIGN KEY (DEPTNO) REFERENCES DEPT1 (DEPTNO),
    CHECK(SAL>0),
    CHECK(COMM>=0)
);

INSERT INTO EMP1 (EMPNO, ENAME, JOB, SAL, DEPTNO)
    VALUES(1111, 'HONG', 'MANAGER', 1000, 10);  -- DEPT1에 부모키의 값이 부재라 오류
INSERT INTO DEPT1 SELECT * FROM DEPT; -- DEPT의 내용을 DEPT1에 입력
INSERT INTO DEPT1 VALUES (40, 'IT', 'SEOUL');  -- 오류 : PK
INSERT INTO DEPT1 (DNAME, LOC) VALUES ('IT', 'SEOUL'); --오류 : PK
SELECT * FROM DEPT1;
INSERT INTO DEPT1 VALUES (50, 'SALES', 'SEOUL'); -- 오류 : UNIQUE
INSERT INTO DEPT1 (DEPTNO, DNAME) VALUES (50, 'IT');  -- 오류 : NOT NULL
DELETE FROM DEPT1 WHERE DEPTNO=50;
INSERT INTO EMP1 (EMPNO, ENAME, JOB, SAL)
    VALUES(1001, 'HONGGGGGGGGG', 'MANAGER', 1500); --오류 : 길이
SELECT * FROM EMP1;

INSERT INTO EMP1 (EMPNO, ENAME, JOB, SAL) VALUES (1002, 'KIM', 'MANAGER', 0); -- CHECK 에러
INSERT INTO EMP1 (EMPNO, ENAME, JOB, SAL) VALUES (1002, 'KIM', 'MANAGER', 1);

------ 연습문제 3
DROP TABLE MAJOR;
CREATE TABLE MAJOR(
    mCODE NUMBER(2) PRIMARY KEY,
    mNAME VARCHAR2(20) NOT NULL,
    mOFFICE VARCHAR2(15)
);

DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    sNO NUMBER(3) PRIMARY KEY,
    sNAME VARCHAR2(12) NOT NULL,
    sSCORE NUMBER(3) CHECK(sSCORE>=0 AND sSCORE<=100),
    mCODE NUMBER(2) REFERENCES MAJOR(mCODE)
);

INSERT INTO MAJOR VALUES (1, '컴퓨터공학', 'A101호');
INSERT INTO MAJOR VALUES (2, '빅데이터', 'A102호');
INSERT INTO STUDENT VALUES (101, '박진성', 100, 1);
INSERT INTO STUDENT VALUES (102, '박하빈', 99, 2);

SELECT SNO 학번, SNAME 이름, SSCORE 점수, S.MCODE 학과코드, MNAME 학과명, MOFFICE 학과사무실
    FROM STUDENT S, MAJOR M
    WHERE S.MCODE = M.MCODE;
