-- [V] Sequence : 순차 번호 생성기. 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH        1 -- 1부터 시작(기본값)
    INCREMENT BY    1 -- 1씩 증가(기본값)
    MAXVALUE         9999   -- 최대값
    MINVALUE          1       -- 최소값
    NOCYCLE   -- CYCLE : 순차번호 9999 -> 1
    NOCACHE;
    
SELECT FRIEND_SEQ.NEXTVAL   --  FRIEND_SEQ 객체를 통해 다음 값을 불러옴
    FROM DUAL;                    -- DUAL은 오라클에서 제공해주는 가상 테이블 (SELECT만 있으면 에러가 나기 때문에)
SELECT 20+50 FROM DUAL;   -- 이런식의 계산식도 가능함

SELECT FRIEND_SEQ.CURRVAL  FROM DUAL;  -- FRIEND_SEQ 객체를 통해 현재 값을 불러옴

DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    TEL VARCHAR2(13) UNIQUE,
    ADDRESS VARCHAR2(50),
    LAST_MODIFY DATE DEFAULT SYSDATE
);

DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE         99999   -- 최대값
    NOCYCLE NOCACHE;
SELECT * FROM FRIEND;

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-8888', '서울');
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '유길동', '010-9999-9999', '서울');
SELECT * FROM FRIEND;

-- 연습문제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMBER_SEQ;

CREATE SEQUENCE MEMBER_SEQ
    MAXVALUE 9999
    NOCYCLE NOCACHE;

CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR(50) NOT NULL    
);

CREATE TABLE MEMBER(
    MNO NUMBER(4) PRIMARY KEY,
    MNAME VARCHAR2(50) NOT NULL,
    MPW VARCHAR2(50) NOT NULL,
    MEMAIL VARCHAR2(50) UNIQUE,
    MPOINT NUMBER(8) CHECK(MPOINT >=0),
    MRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(1) REFERENCES MEMBER_LEVEL(LEVELNO)
);

SELECT * FROM MEMBER;
SELECT * FROM MEMBER_LEVEL;

INSERT INTO MEMBER_LEVEL 
    VALUES (-1, 'BLACK');
INSERT INTO MEMBER_LEVEL 
    VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL 
    VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL 
    VALUES (2, '골드');
SELECT * FROM MEMBER_LEVEL;

INSERT INTO MEMBER 
    VALUES (member_seq.nextval, '홍길동', 'aa', 'HONG@HONG.com', 0, TO_DATE('24/09/26', 'RR/MM/DD'), 0);
INSERT INTO MEMBER 
    VALUES (member_seq.nextval, '신길동', 'bb', 'sin@sin.com', 1000, TO_DATE('22/04/01', 'RR/MM/DD'), 1);
    
SELECT MNO "mNO", MNAME "mNAME", TO_CHAR(MRDATE, 'YYYY-MM-DD') "mRDATE", MEMAIL "mMAIL", MPOINT "point", L.LEVELNAME || '고객' "levelname" 
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO = L.LEVELNO;